sdkversion: "4.0.0"
name: "REHC"
version: "1.0"
# change this to modify the package name under android
vendor: "rhomobile"
build: "debug"
bbver: "6.0"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.rehc"
  BundleURLScheme: "rehc"
wp:
  productid: "d2c47ba0-1df4-0131-80c7-000c292a2cb8"
symbian:
  uid: "0xe6f6ab1e"
android:
  version: "2.3.3"
  emulator: "rhoAndroid21"
  android_title: 0
  orientation: "portrait"
  capabilities: 
# Use this to set certificate for Android sproduction build
#  production:
#    certificate: path/to/your/developer/certificate
#    password: "password-of-the-certificate"
#    alias: "keystore.alias"
extensions:
  - barcode
  - externalstorage
  - rexml
  - set
  - wifi_config
  - hardwarekeys
app_type: "rhoelements"
capabilities:
  - sdcard
